### ISSUE TITLE
Generate from selection in document generation

### ISSUE THREAD

**Issue by deshetti** [factly/scooter#48]
Refers to the following feature in Notion when a selection is made on the existing content:

![Image](https://github.com/factly/scooter/assets/10763210/2ea3ef11-bd40-418f-98d4-297517529e0c)

**Comment by deshetti** [comment]
Refers to the following feature in Notion when a selection is made on the existing content:


![Image](https://github.com/factly/scooter/assets/10763210/2ea3ef11-bd40-418f-98d4-297517529e0c)

**Comment by fyrepenguin** [comment]
closed in #67
