### ISSUE TITLE
Reduce Scooter package size

### ISSUE THREAD

**Issue by fyrepenguin** [factly/scooter#73]
make other extensions and their packages optional to include
uppy, image, embed, table should be added manually instead of existing by default.

**Comment by surajmn1** [comment]
@fyrepenguin 
i have few queries related to this issue :
1) how should we go about doing this from a code perspective ? 
- how to go about decoupling the extensions, which are currently being imported and added in the useCustomExtension.js 
  file by default? 
- few extensions have a ui part (currently coupled with scooter-core ui (ex:ImageUploader component) as well along with it.
  how to go about adding the ui components of the extensions as well along with the extension.
- how do we go about adding and removing menu options in various menus we support, when we add or remove 
   extensions?
2) how should we go about separating the scooter.core scss style sheet ? 
3) what packages would be part of the `core` and what should be manually added ? should few `menu` packages also be 
    optional ?

**Comment by fyrepenguin** [comment]
We have to add the optional packages using custom extensions prop. Same for Menu Items using a menu items prop, I don't recall exact prop names for those, but can get back to you about those tomorrow if needed. But for specific extension based components, we can check whether the extension exists or not from the editor instance and enable or disable them based on that.

**Comment by surajmn1** [comment]
so you mean to say the`ImageUploader` component which is a `scooter-image` extension based component, will have to remain as part of the core ui but conditionally rendered ? but in cases were i am not using the image extension we will still have the scooter-image extension package loaded , as the core would require `ImageUploader` component, is there any way around this ?

**Comment by surajmn1** [comment]
@fyrepenguin 
please also address the Core Stylesheet Separation issue and package related (2,3) queries in my earlier comment. we appreciate if you can get back to us with more details on them and the extension based components issue i mentioned in my reply to you. thanks .

**Comment by surajmn1** [comment]
@fyrepenguin currently im thinking of a way to go about handling the case were we have extension based ui components
1) we would have single extension object exported from the package which would have below or we could compose the 
    custom extension prop to have 
       - extension 
       - extension based ui 
   we would go about destructuring this object internally and render the extension based ui as children over the editor.
   state variables associated with conditionally rendering the extension ui remain within the editor core , so 
   in future to support extensions with ui we would have to add only state variables related to them in the core and associate 
   them with the respective ui, based on whether the extension is present or not.
